### PR TITLE
Initial generation of base files

### PR DESCRIPTION
**Pull request by Szsaunders**

### CODE REVIEW

**Comment by Szsaunders** [comment]
I only reverted a couple of later commits that went outside the scope of this branch's specific feature/chore (while moving them to a more appropriate branch). The base project files created via 'ng generate' are still committed, and that's all I intend to merge into broker via this branch.

**Comment by escalonn** [comment]
look at "files changed" tab - there are 0 lines difference between this branch and broker
look at commits tab - 3 commits, followed by 3 reverts of those 3.

you may want to revert `1fb8e76` to get back the files you originally committed to `master`?

**Comment by Szsaunders** [comment]
Angular.json updated. License created. I think that's everything except Dockerfiles (which I'll implement as soon as Team 2 finishes setting up the pipeline) and documentation.

**Comment by Szsaunders** [comment]
Okay, Angular.json's been updated, ci files have been added, and a license has been created. Everything should be set except for Dockerfiles and documentation.

**Pull request merged**
